services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile_backend
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
    image: ${DOCKER_USER}/be-${IMAGE_NAME}:${VERSION}
    ports:
      - "5000:5000"
    environment:
      # ตั้งค่า environment variables ที่ backend ต้องการ
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
      FLASK_ENV: development # หรือ production
    volumes:
      - ./backend:/app # สำหรับ Development, เพื่อให้โค้ด sync อัตโนมัติ

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile_frontend
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
    image: ${DOCKER_USER}/fe-${IMAGE_NAME}:${VERSION}
    ports:
      - "80:80"
    depends_on:
      - backend # ทำให้ frontend service รอ backend service ให้พร้อมก่อน
    volumes:
      - ./frontend:/app # สำหรับ Development, ถ้าต้องการให้ Vite HMR ทำงาน
    environment:
      # สำหรับ React Development: ตั้งค่าเพื่อให้ Vite HMR ทำงาน
      # ต้องตรวจสอบว่า Vite กำหนด VITE_API_URL หรือคล้ายกัน
      # ถ้าใช้ Nginx Proxy Pass ตัวนี้ไม่จำเป็นสำหรับ Production Build
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
      VITE_API_URL: http://localhost:5000/api