apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ${DOCKER_USER}/be-${IMAGE_NAME}:${VERSION}
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
      # ถ้ามี Worker Node ให้เอา tolerations ออก
      tolerations: #ทำให้อนุญาติการทำงานสร้าง pod ในเครื่อง master node ได้
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
